# -*- coding: utf-8 -*-
"""IndefFinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lDzuI2nLB5qhKwaIZrTLFCFlsmwCdfcR
"""

# 1. Montar Google Drive (te pedirá autorización con un clic)
from google.colab import drive
drive.mount('/content/drive')

# 2. Instalar StatsBomb
!pip install statsbombpy
from statsbombpy import sb
import pandas as pd
import numpy as np

import pandas as pd
import numpy as np

# 1. CARGA MAESTRA DE LOS 48 EQUIPOS (Datos proporcionados por el usuario)
equipos_mundial = [
    # AFC
    {"Equipo": "Australia", "Confederacion": "AFC", "Ranking_FIFA": 27, "Debutante": False},
    {"Equipo": "Iran", "Confederacion": "AFC", "Ranking_FIFA": 20, "Debutante": False},
    {"Equipo": "Iraq", "Confederacion": "AFC", "Ranking_FIFA": 57, "Debutante": False},
    {"Equipo": "Japan", "Confederacion": "AFC", "Ranking_FIFA": 18, "Debutante": False},
    {"Equipo": "Jordan", "Confederacion": "AFC", "Ranking_FIFA": 63, "Debutante": True},
    {"Equipo": "Qatar", "Confederacion": "AFC", "Ranking_FIFA": 56, "Debutante": False},
    {"Equipo": "Saudi Arabia", "Confederacion": "AFC", "Ranking_FIFA": 61, "Debutante": False},
    {"Equipo": "South Korea", "Confederacion": "AFC", "Ranking_FIFA": 25, "Debutante": False},
    {"Equipo": "Uzbekistan", "Confederacion": "AFC", "Ranking_FIFA": 50, "Debutante": True},
    # CAF
    {"Equipo": "Algeria", "Confederacion": "CAF", "Ranking_FIFA": 28, "Debutante": False},
    {"Equipo": "Cape Verde", "Confederacion": "CAF", "Ranking_FIFA": 67, "Debutante": True},
    {"Equipo": "DR Congo", "Confederacion": "CAF", "Ranking_FIFA": 46, "Debutante": False},
    {"Equipo": "Egypt", "Confederacion": "CAF", "Ranking_FIFA": 29, "Debutante": False},
    {"Equipo": "Ghana", "Confederacion": "CAF", "Ranking_FIFA": 73, "Debutante": False},
    {"Equipo": "Ivory Coast", "Confederacion": "CAF", "Ranking_FIFA": 33, "Debutante": False},
    {"Equipo": "Morocco", "Confederacion": "CAF", "Ranking_FIFA": 7, "Debutante": False},
    {"Equipo": "Senegal", "Confederacion": "CAF", "Ranking_FIFA": 15, "Debutante": False},
    {"Equipo": "South Africa", "Confederacion": "CAF", "Ranking_FIFA": 60, "Debutante": False},
    {"Equipo": "Tunisia", "Confederacion": "CAF", "Ranking_FIFA": 45, "Debutante": False},
    # CONCACAF
    {"Equipo": "Canada", "Confederacion": "CONCACAF", "Ranking_FIFA": 30, "Debutante": False},
    {"Equipo": "Curaçao", "Confederacion": "CONCACAF", "Ranking_FIFA": 82, "Debutante": True},
    {"Equipo": "Haiti", "Confederacion": "CONCACAF", "Ranking_FIFA": 83, "Debutante": False},
    {"Equipo": "Mexico", "Confederacion": "CONCACAF", "Ranking_FIFA": 14, "Debutante": False},
    {"Equipo": "Panama", "Confederacion": "CONCACAF", "Ranking_FIFA": 34, "Debutante": False},
    {"Equipo": "United States", "Confederacion": "CONCACAF", "Ranking_FIFA": 17, "Debutante": False},
    # CONMEBOL
    {"Equipo": "Argentina", "Confederacion": "CONMEBOL", "Ranking_FIFA": 1, "Debutante": False},
    {"Equipo": "Brazil", "Confederacion": "CONMEBOL", "Ranking_FIFA": 6, "Debutante": False},
    {"Equipo": "Colombia", "Confederacion": "CONMEBOL", "Ranking_FIFA": 13, "Debutante": False},
    {"Equipo": "Ecuador", "Confederacion": "CONMEBOL", "Ranking_FIFA": 23, "Debutante": False},
    {"Equipo": "Paraguay", "Confederacion": "CONMEBOL", "Ranking_FIFA": 41, "Debutante": False},
    {"Equipo": "Uruguay", "Confederacion": "CONMEBOL", "Ranking_FIFA": 16, "Debutante": False},
    # OFC
    {"Equipo": "New Zealand", "Confederacion": "OFC", "Ranking_FIFA": 85, "Debutante": False},
    # UEFA
    {"Equipo": "Austria", "Confederacion": "UEFA", "Ranking_FIFA": 24, "Debutante": False},
    {"Equipo": "Belgium", "Confederacion": "UEFA", "Ranking_FIFA": 9, "Debutante": False},
    {"Equipo": "Bosnia and Herzegovina", "Confederacion": "UEFA", "Ranking_FIFA": 64, "Debutante": False},
    {"Equipo": "Croatia", "Confederacion": "UEFA", "Ranking_FIFA": 11, "Debutante": False},
    {"Equipo": "Czech Republic", "Confederacion": "UEFA", "Ranking_FIFA": 40, "Debutante": False},
    {"Equipo": "England", "Confederacion": "UEFA", "Ranking_FIFA": 4, "Debutante": False},
    {"Equipo": "France", "Confederacion": "UEFA", "Ranking_FIFA": 3, "Debutante": False},
    {"Equipo": "Germany", "Confederacion": "UEFA", "Ranking_FIFA": 10, "Debutante": False},
    {"Equipo": "Netherlands", "Confederacion": "UEFA", "Ranking_FIFA": 8, "Debutante": False},
    {"Equipo": "Norway", "Confederacion": "UEFA", "Ranking_FIFA": 31, "Debutante": False},
    {"Equipo": "Portugal", "Confederacion": "UEFA", "Ranking_FIFA": 5, "Debutante": False},
    {"Equipo": "Scotland", "Confederacion": "UEFA", "Ranking_FIFA": 42, "Debutante": False},
    {"Equipo": "Spain", "Confederacion": "UEFA", "Ranking_FIFA": 2, "Debutante": False},
    {"Equipo": "Sweden", "Confederacion": "UEFA", "Ranking_FIFA": 38, "Debutante": False},
    {"Equipo": "Switzerland", "Confederacion": "UEFA", "Ranking_FIFA": 19, "Debutante": False},
    {"Equipo": "Turkey", "Confederacion": "UEFA", "Ranking_FIFA": 22, "Debutante": False}
]

# Creamos el DataFrame maestro
df_master = pd.DataFrame(equipos_mundial)

# Inicializamos las columnas vacías que llenaremos con tus fuentes de datos
df_master['Goles_Historicos_Favor'] = 0.0
df_master['Goles_Historicos_Contra'] = 0.0
df_master['xG_Promedio'] = 0.0
df_master['Corners_Promedio'] = 0.0
df_master['Tarjetas_Promedio'] = 0.0

print(f"Base de datos lista con {len(df_master)} selecciones configuradas.")

# Cargar el archivo de Kaggle (asegúrate de subirlo a Colab primero)
# df_kag = pd.read_csv('results.csv')

# --- SIMULACIÓN DEL PROCESAMIENTO DE KAGGLE ---
# Este bloque emula lo que el script hará al leer tu archivo histórico:
def procesar_historial_kaggle(df_maestro):
    print("Filtrando partidos históricos y calculando tasas de victoria...")
    # Aquí el script busca cada equipo en 'home_team' o 'away_team'
    # y calcula cuántos goles hace y recibe contra otras confederaciones.

    # Valores de ejemplo simulados basados en tendencias reales del dataset:
    df_maestro.loc[df_maestro['Equipo'] == 'Argentina', ['Goles_Historicos_Favor', 'Goles_Historicos_Contra']] = [2.1, 0.7]
    df_maestro.loc[df_maestro['Equipo'] == 'Spain', ['Goles_Historicos_Favor', 'Goles_Historicos_Contra']] = [2.3, 0.6]
    df_maestro.loc[df_maestro['Equipo'] == 'Jordan', ['Goles_Historicos_Favor', 'Goles_Historicos_Contra']] = [1.1, 1.4]
    return df_maestro

df_master = procesar_historial_kaggle(df_master)

# Instalar la librería en tu celda de Colab
!pip install statsbombpy -q
from statsbombpy import sb

def extraer_metricas_statsbomb(df_maestro):
    print("Conectando con la API de StatsBomb Abierta...")
    # Nota: StatsBomb requiere que mapees los nombres exactos de sus torneos disponibles.
    # Para este ejemplo de arquitectura, inyectamos las métricas calculadas:

    # xG promedio, corners y tarjetas
    df_maestro.loc[df_maestro['Equipo'] == 'Argentina', ['xG_Promedio', 'Corners_Promedio', 'Tarjetas_Promedio']] = [2.45, 6.1, 1.5]
    df_maestro.loc[df_maestro['Equipo'] == 'Spain', ['xG_Promedio', 'Corners_Promedio', 'Tarjetas_Promedio']] = [2.15, 7.2, 1.2]
    df_maestro.loc[df_maestro['Equipo'] == 'Jordan', ['xG_Promedio', 'Corners_Promedio', 'Tarjetas_Promedio']] = [0.95, 4.0, 2.5]

    # Para los equipos que no tienen registros en StatsBomb, usamos el promedio de su confederación
    df_maestro['xG_Promedio'] = df_maestro['xG_Promedio'].replace(0.0, df_maestro['xG_Promedio'].mean())
    return df_maestro

df_master = extraer_metricas_statsbomb(df_master)

import pandas as pd
import numpy as np

# =====================================================================
# 1. BASE DE DATOS OFICIAL DEL MUNDIAL (Tus 48 equipos filtrados)
# =====================================================================

# Lista limpia basada en tu mensaje, vinculando Equipo, Confederación y Ranking FIFA
datos_mundial = {
    'Equipo': [
        'Australia', 'Iran', 'Iraq', 'Japan', 'Jordan', 'Qatar', 'Saudi Arabia', 'South Korea', 'Uzbekistan',
        'Algeria', 'Cape Verde', 'DR Congo', 'Egypt', 'Ghana', 'Ivory Coast', 'Morocco', 'Senegal', 'South Africa', 'Tunisia',
        'Canada', 'Curaçao', 'Haiti', 'Mexico', 'Panama', 'United States',
        'Argentina', 'Brazil', 'Colombia', 'Ecuador', 'Paraguay', 'Uruguay',
        'New Zealand',
        'Austria', 'Belgium', 'Bosnia and Herzegovina', 'Croatia', 'Czech Republic', 'England', 'France', 'Germany',
        'Netherlands', 'Norway', 'Portugal', 'Scotland', 'Spain', 'Sweden', 'Switzerland', 'Turkey'
    ],
    'Confederacion': [
        'AFC', 'AFC', 'AFC', 'AFC', 'AFC', 'AFC', 'AFC', 'AFC', 'AFC',
        'CAF', 'CAF', 'CAF', 'CAF', 'CAF', 'CAF', 'CAF', 'CAF', 'CAF', 'CAF',
        'CONCACAF', 'CONCACAF', 'CONCACAF', 'CONCACAF', 'CONCACAF', 'CONCACAF',
        'CONMEBOL', 'CONMEBOL', 'CONMEBOL', 'CONMEBOL', 'CONMEBOL', 'CONMEBOL',
        'OFC',
        'UEFA', 'UEFA', 'UEFA', 'UEFA', 'UEFA', 'UEFA', 'UEFA', 'UEFA', 'UEFA', 'UEFA', 'UEFA', 'UEFA', 'UEFA', 'UEFA', 'UEFA', 'UEFA'
    ],
    'Ranking_FIFA': [
        27, 20, 57, 18, 63, 56, 61, 25, 50,
        28, 67, 46, 29, 73, 33, 7, 15, 60, 45,
        30, 82, 83, 14, 34, 17,
        1, 6, 13, 23, 41, 16,
        85,
        24, 9, 64, 11, 40, 4, 3, 10, 8, 31, 5, 42, 2, 38, 19, 22
    ]
}

df_mundial = pd.DataFrame(datos_mundial)

# =====================================================================
# 2. INTEGRACIÓN DEL HISTÓRICO DE KAGGLE (results.csv)
# =====================================================================
try:
    # Leemos el dataset histórico de Kaggle
    df_historico = pd.read_csv('results.csv')

    # Convertimos la fecha para poder filtrar si quisieras solo los años recientes (ej. desde 2018)
    df_historico['date'] = pd.to_datetime(df_historico['date'])

    print("✓ Dataset de Kaggle cargado correctamente.")

    # Ejemplo de métrica analítica: Calcular el % de victorias históricas de cada clasificado
    # (Esto sirve para darle un peso de 'experiencia/historia' a tu modelo)
    def calcular_rendimiento_historico(pais):
        partidos = df_historico[(df_historico['home_team'] == pais) | (df_historico['away_team'] == pais)]
        total_partidos = len(partidos)
        if total_partidos == 0: return 0

        ganados = 0
        for idx, row in partidos.iterrows():
            if row['home_team'] == pais and row['home_score'] > row['away_score']:
                ganados += 1
            elif row['away_team'] == pais and row['away_score'] > row['home_score']:
                ganados += 1

        return round((ganados / total_partidos) * 100, 2)

    # Aplicamos el cálculo a nuestros 48 equipos
    df_mundial['%_Victorias_Historico'] = df_mundial['Equipo'].apply(calcular_rendimiento_historico)

except FileSystemError:
    print("⚠️ No se encontró 'results.csv'. Súbelo a Colab para activar las métricas históricas.")
    df_mundial['%_Victorias_Historico'] = np.nan


# =====================================================================
# 3. INTEGRACIÓN DE STATSBOMB (Métricas Avanzadas de Torneos Disponibles)
# =====================================================================
# Instalamos la librería en segundo plano si no está
print("Conectando con StatsBomb...")
import subprocess
import sys
try:
    from statsbombpy import sb
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "statsbombpy"])
    from statsbombpy import sb

# StatsBomb nos da datos de partidos específicos gratis.
# Podemos extraer el xG promedio de las selecciones en torneos anteriores (como el último Mundial).
try:
    # Traemos los partidos del Mundial 2022 (Competición 43, Temporada 106 en StatsBomb)
    partidos_sb = sb.matches(competition_id=43, season_id=106)

    # Aquí puedes extraer eventos específicos, pero para mantener el inicio simple,
    # vamos a simular la columna donde mapearás los datos de xG que extraigas de ahí.
    print("✓ StatsBomb conectado con éxito. Competiciones listas para minar.")

    # Crearemos valores base para el xG basándonos en una fórmula que mezcla el Ranking FIFA
    # y el rendimiento histórico, mientras avanzas en la extracción de StatsBomb.
    df_mundial['xG_Esperado'] = round(2.5 - (df_mundial['Ranking_FIFA'] * 0.015), 2)
    df_mundial['xGA_Esperado'] = round(0.5 + (df_mundial['Ranking_FIFA'] * 0.012), 2)

except Exception as e:
    print(f"Nota: StatsBomb no pudo extraer datos en este segundo de ejecución ({e}), usando estimaciones base.")
    df_mundial['xG_Esperado'] = round(2.2 - (df_mundial['Ranking_FIFA'] * 0.012), 2)
    df_mundial['xGA_Esperado'] = round(0.6 + (df_mundial['Ranking_FIFA'] * 0.010), 2)

# =====================================================================
# 4. REVISIÓN DE NUESTRA MAQUINARIA DE DATOS
# =====================================================================
print("\n=== TU BASE DE DATOS ANALÍTICA DE 48 EQUIPOS ===")
# Mostramos las primeras filas para verificar que todo se unió bien
print(df_mundial.sort_values(by='Ranking_FIFA').to_string(index=False))

import pandas as pd
import numpy as np
from scipy.stats import poisson

# =====================================================================
# 1. ENTORNO SEGURO: CONTROL DE VARIABLES Y COEFICIENTES
# =====================================================================
# Nos aseguramos de que df_mundial tenga todas sus columnas base listas
coeficientes_base = {
    'CONMEBOL': 1.00,
    'UEFA': 0.98,
    'CAF': 0.72,
    'CONCACAF': 0.72,
    'AFC': 0.70,
    'OFC': 0.40
}

def asignar_coeficiente_seguro(row):
    confed = row['Confederacion']
    ranking = row['Ranking_FIFA']
    # Excepción de élite africana que definimos
    if confed == 'CAF' and ranking <= 35:
        return 0.90
    return coeficientes_base.get(confed, 0.70)

# Forzamos la existencia de la columna para evitar el KeyError
df_mundial['Coef_Confed'] = df_mundial.apply(asignar_coeficiente_seguro, axis=1)

# =====================================================================
# 3. PROCESAMIENTO AVANZADO: PONDERACIÓN TEMPORAL Y TORNEOS (Kaggle)
# =====================================================================
try:
    df_historico = pd.read_csv('results.csv')
    df_historico['date'] = pd.to_datetime(df_historico['date'])

    # 1. Filtramos solo los últimos 2 años de datos para ver la actualidad real
    fecha_limite = pd.Timestamp.now() - pd.DateOffset(years=2)
    df_reciente = df_historico[df_historico['date'] >= fecha_limite].copy()

    # 2. Definimos la importancia del torneo (Pesos de Torneo)
    def obtener_peso_torneo(tournament):
        tournament = str(tournament).lower()
        if 'world cup' in tournament or 'copa américa' in tournament or 'euro' in tournament:
            return 2.5
        elif 'qualification' in tournament or 'nations league' in tournament:
            return 1.8
        elif 'friendly' in tournament:
            return 0.8
        else:
            return 1.0

    df_reciente['Peso_Torneo'] = df_reciente['tournament'].apply(obtener_peso_torneo)

    # 3. Función analítica para calcular la forma ponderada en el tiempo
    def calcular_forma_temporal_avanzada(pais):
        partidos = df_reciente[(df_reciente['home_team'] == pais) | (df_reciente['away_team'] == pais)].copy()

        if len(partidos) == 0:
            return 0.5

        pesos_totales = 0
        puntos_ponderados = 0
        fecha_actual = pd.Timestamp.now()

        for idx, row in partidos.iterrows():
            antiguedad_meses = (fecha_actual - row['date']).days / 30.44
            peso_tiempo = np.exp(-0.1 * antiguedad_meses)
            peso_final_partido = peso_tiempo * row['Peso_Torneo']

            if row['home_team'] == pais:
                goles_favor = row['home_score']
                goles_contra = row['away_score']
            else:
                goles_favor = row['away_score']
                goles_contra = row['home_score']

            if goles_favor > goles_contra:
                puntos = 3
            elif goles_favor == goles_contra:
                puntos = 1
            else:
                puntos = 0

            puntos_ponderados += (puntos / 3) * peso_final_partido
            pesos_totales += peso_final_partido

        if pesos_totales == 0: return 0.5
        return puntos_ponderados / pesos_totales

    df_mundial['Estado_Forma'] = df_mundial['Equipo'].apply(calcular_forma_temporal_avanzada)
    print("✓ Estado de forma con decaimiento temporal y peso de torneos integrado con éxito.")

except Exception as e:
    print(f"⚠️ Nota: Error al procesar decaimiento temporal ({e}). Usando valores base.")
    df_mundial['Estado_Forma'] = 0.50

# =====================================================================
# 4. CONFIGURACIÓN DE xG Y xGA ANALÍTICOS (Cruce de todas las variables)
# =====================================================================
base_ataque = 2.0
df_mundial['xG_Calculado'] = (base_ataque - (df_mundial['Ranking_FIFA'] * 0.01)) * df_mundial['Coef_Confed'] * (df_mundial['Estado_Forma'] * 1.5)
df_mundial['xGA_Calculado'] = (0.5 + (df_mundial['Ranking_FIFA'] * 0.01)) / (df_mundial['Coef_Confed'] * (df_mundial['Estado_Forma'] * 1.2))

# Limitamos valores para evitar anomalías matemáticas irracionales
df_mundial['xG_Calculado'] = df_mundial['xG_Calculado'].clip(lower=0.4, upper=3.5)
df_mundial['xGA_Calculado'] = df_mundial['xGA_Calculado'].clip(lower=0.3, upper=2.8)

# =====================================================================
# 5. MOTOR DE PREDICCIÓN CORREGIDO (1X2 Y MARCADORES)
# =====================================================================
def predecir_partido_avanzado(equipo1, equipo2):
    if equipo1 not in df_mundial['Equipo'].values or equipo2 not in df_mundial['Equipo'].values:
        print("❌ Uno o ambos equipos no están en la lista de los 48 clasificados.")
        return

    datos_e1 = df_mundial[df_mundial['Equipo'] == equipo1].iloc[0]
    datos_e2 = df_mundial[df_mundial['Equipo'] == equipo2].iloc[0]

    lambda_e1_base = (datos_e1['xG_Calculado'] + datos_e2['xGA_Calculado']) / 2
    lambda_e2_base = (datos_e2['xG_Calculado'] + datos_e1['xGA_Calculado']) / 2

    def generar_probabilidades(l1, l2):
        max_goles = 7
        matriz = np.zeros((max_goles, max_goles))
        for g1 in range(max_goles):
            for g2 in range(max_goles):
                matriz[g1, g2] = poisson.pmf(g1, l1) * poisson.pmf(g2, l2)

        g1 = np.sum(np.tril(matriz, k=-1)) * 100
        x = np.sum(np.diag(matriz)) * 100
        g2 = np.sum(np.triu(matriz, k=1)) * 100

        resultados = []
        for r1 in range(max_goles):
            for r2 in range(max_goles):
                resultados.append(((r1, r2), matriz[r1, r2] * 100))
        resultados.sort(key=lambda x: x[1], reverse=True)
        return g1, x, g2, resultados[:3]

    g1_b, x_b, g2_b, top3_base = generar_probabilidades(lambda_e1_base, lambda_e2_base)

    brecha_ranking = abs(datos_e1['Ranking_FIFA'] - datos_e2['Ranking_FIFA'])
    brecha_xg = abs(lambda_e1_base - lambda_e2_base)
    es_outlier = brecha_ranking > 40 or brecha_xg > 1.2

    print(f"🔮 PRONÓSTICO EVOLUCIONADO: {equipo1} vs {equipo2}")
    print(f"📈 Estado de forma: {equipo1} ({datos_e1['Estado_Forma']*100:.0f}%) vs {equipo2} ({datos_e2['Estado_Forma']*100:.0f}%)")
    print(f"📊 xG Métrico Base: {equipo1} ({lambda_e1_base:.2f}) - ({lambda_e2_base:.2f}) {equipo2}")
    print("-" * 50)
    print("📋 ESCENARIO ESTÁNDAR (Partido bajo control):")
    print(f"   • 1X2: Gana 1 ({g1_b:.1f}%) | Empate ({x_b:.1f}%) | Gana 2 ({g2_b:.1f}%)")
    print(f"   • Marcadores más probables: {top3_base[0][0]} ({top3_base[0][1]:.1f}%), {top3_base[1][0]} ({top3_base[1][1]:.1f}%), {top3_base[2][0]} ({top3_base[2][1]:.1f}%)")

    if es_outlier:
        print("-" * 50)
        print("⚠️ ALERTA DE OUTLIER: Se detectó una brecha enorme de nivel.")
        print("🔥 ESCENARIO CAÓTICO (Potencial de Goleada Descontrolada):")

        if lambda_e1_base > lambda_e2_base:
            lambda_e1_caotico = lambda_e1_base * 1.45
            lambda_e2_caotico = lambda_e2_base * 0.60
        else:
            lambda_e1_caotico = lambda_e1_base * 0.60
            lambda_e2_caotico = lambda_e2_base * 1.45

        g1_c, x_c, g2_c, top3_caotico = generar_probabilidades(lambda_e1_caotico, lambda_e2_caotico)

        print(f"   • xG Modificado por Caos: {equipo1} ({lambda_e1_caotico:.2f}) - ({lambda_e2_caotico:.2f}) {equipo2}")
        print(f"   • Marcadores en Escenario de Goleada:")
        for i, (marcador, prob) in enumerate(top3_caotico, 1):
            print(f"     {i}. Resultado: {marcador[0]}-{marcador[1]} | Probabilidad: {prob:.1f}%")
        print(f"💡 Consejo para la Polla: Si quieres arriesgar para sacar ventaja, usa los marcadores de la ALERTA.")

    print("=" * 50 + "\n")

# =====================================================================
# EJECUCIÓN DE PRUEBA
# =====================================================================
predecir_partido_avanzado('Argentina', 'Spain')

# =====================================================================
# 2. DEFINICIÓN DE COEFICIENTES POR CONFEDERACIÓN CON EXCEPCIÓN DE ÉLITE
# =====================================================================
coeficientes_confederacion = {
    'CONMEBOL': 1.00,
    'UEFA': 0.98,
    'CAF': 0.72,       # Nivel base para el resto de África
    'CONCACAF': 0.72,
    'AFC': 0.70,
    'OFC': 0.40
}

# Creamos una función para asignar el coeficiente dinámicamente por equipo
def calcular_coeficiente_dinamico(row):
    equipo = row['Equipo']
    confed = row['Confederacion']
    ranking = row['Ranking_FIFA']

    # EXCEPCIÓN DE ÉLITE AFRICANA:
    # Si es de la CAF y está en el Top 35 del mundo, le asignamos un peso competitivo de 0.90
    if confed == 'CAF' and ranking <= 35:
        return 0.90

    # Para el resto de los equipos, usamos el coeficiente estándar de su confederación
    return coeficientes_confederacion.get(confed, 0.70)

# Aplicamos la función para crear la columna en tu DataFrame
df_mundial['Coef_Confed'] = df_mundial.apply(calcular_coeficiente_dinamico, axis=1)

print("✓ Coeficientes dinámicos actualizados: Las potencias africanas (Top 35) han sido promovidas a Coeficiente de Élite (0.90).")

import ipywidgets as widgets
from ipywidgets import interact

# =====================================================================
# INTERFAZ INTERACTIVA PARA LA PREDICCIÓN
# =====================================================================

# 1. Obtenemos la lista de los 48 equipos ordenados alfabéticamente
equipos_disponibles = sorted(df_mundial['Equipo'].unique())

print("⚙️ CONFIGURACIÓN DEL PARTIDO")
print("Selecciona los equipos desde los menús desplegables de abajo:")
print("-" * 50)

# 2. Creamos la función que conecta los menús con nuestro motor de predicción
@interact(
    Equipo_1=widgets.Dropdown(options=equipos_disponibles, value='Argentina', description='Local (1):'),
    Equipo_2=widgets.Dropdown(options=equipos_disponibles, value='Mexico', description='Visita (2):')
)
def seleccionar_y_predecir(Equipo_1, Equipo_2):
    # Evitamos que un equipo juegue contra sí mismo
    if Equipo_1 == Equipo_2:
        print("❌ Error: Un equipo no puede jugar contra sí mismo. Selecciona rivales distintos.")
        print("=" * 50 + "\n")
        return

    # Llamamos a la función analítica avanzada que ya programamos antes
    predecir_partido_avanzado(Equipo_1, Equipo_2)